### ISSUE TITLE
Build Error Gradle version 7.1, Java 16

### ISSUE THREAD

**Issue by samuelgoodall** [bft-smart/library#107]
With the latest changes made to the master branch, I get the following Issue when attempting to build the project:

Could not get unknown property 'remoteDeployMasterHost' for master[null:22] of type org.hidetake.groovy.ssh.core.Remote.

Steps to reproduce:
- clone Project
- build project with ./gradlew installDist

System used:
- OS: Win 10 
- JRE: Amazon Coretto 16
- Gradle version 7.1 provided in the Gradle wrapper.

when I change this in the build.gradle: 
master {
		//Create a gradle.properties and set the following properties: remoteDeployMasterHost, remoteDeployMasterUser,
		// remoteDeployMasterPrivateKeyFile
		host = remoteDeployMasterHost
		user = remoteDeployMasterUser
		identity = file(remoteDeployMasterPrivateKeyFile)
	}
back to this:
master {
		host = '<ip>'
		user = '<username>'
		//password = '<password>'
		identity=file('<private key file>')
	}
it works again.
as found in Revision number: e0399ca0a2e5eed7b30c1b093b3f82d7250332af
Revision: e0399ca0

Regards,
Samuel Goodall

**Comment by rvassantlal** [comment]
Thanks for letting us know about the issue. I have corrected it, and I also have fixed other bugs. I recommend you use the latest commit on the master branch.
