### ISSUE TITLE
throuput of benchmark

### ISSUE THREAD

**Issue by qingxiao1999** [bft-smart/library#109]
I have tested the benchmark and Increased the number of nodes to 50, however the throuput of server didn't decrease as I expected.  The throuput of server remains around 850 ops/sec. I wonder if this is because the network delay is not taken into account in the benchmark？ To solve this，I wonder if i have to run the benchmark in the real scenarios or modiy the code to simulate the network environment？

**Comment by rvassantlal** [comment]
I do not fully understand your issue.
I always measure the library's performance in a real network, but never with that many nodes.
Are you running the benchmark locally? If yes, then you have to simulate the network somehow.

Sorry for the late response.

**Comment by rvassantlal** [comment]
I am closing this issue because I haven't received a further response. If you still have a problem, please feel free to reopen this issue.
