### ISSUE TITLE
The cleanAsynchRequest method of the AsynchServiceProxy causes a NullPointerException

### ISSUE THREAD

**Issue by lxndrHss** [bft-smart/library#115]
The invocation of the `bftsmart.tom.AsynchServiceProxy.cleanAsyncRequest` method leads to a `NullPointerException` in the `bftsmart.tom.ServiceProxy.replyReceived` method if it is invoked before all replies have been received and processed.
Since this method should be invoked after are quorum of matching replies have been received this issue will appear permanently.

This behaviour is a consequence of a change made in Commit 2bb506b08695f3d29d0d624502997ab296b12be4, where a filter for late arriving replies has been removed from the `bftsmart.tom.ServiceProxy.replyReceived` method.
Without this check, an asynchronous reply that is processed after the `cleanAsynchRequest` method is invoked is treated as a synchronous reply, and since there is no requestHandler object present this leads to `NullPointerException`.

This issue can easily be replicated using the `bftsmart.demo.microbenchmarks.AsyncLatencyClient` in the BFT-SMaRt v2.0 release version without any modification.

**Comment by rvassantlal** [comment]
Issue has been resolved in the recent commit to the master branch. Thank you for reporting the problem!
