### ISSUE TITLE
DefaultRecoverable is the only stable executor/recoverer

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bft-smart/library#16]
```
DefaultSingleRecoverer apperantly is unable to process requests and 
DurabilityCoordinator's state transfer is unstable.

The only executor/recoverer that offer satisfactory stability is 
DefaultRecoverable.Until we properly test/fix the others, we have to include a 
not in the readme file warning users about this issue.

```

Original issue reported on code.google.com by `liquidsn...@sapo.pt` on 26 Jan 2015 at 6:20

**Comment by chetmurthy** [comment]
Hi, I just hit this problem, and found the admonition in README (who reads those things! *grin*), so I'm back to using DefaultRecoverable.  But for my little project, I -surely- would like to use DurabilityCoordinator.  If it's already in the process of getting fixed, I should just wait.  But if not, and if there were any pointers to how to go about debugging, I'd be happy to try to fix it.

I'm pretty familiar with Paxos-based distributed systems, and with stuff in the ISIS/Horus/Ensemble world.  But not so familiar with BFT.
