### ISSUE TITLE
Livelock after partitioning 1 node?

### ISSUE THREAD

**Issue by amiller** [bft-smart/library#19]
I’m trying to understand how BFT-SMaRt behaves under some adversarial schedulers.

I hacked the code so that the servers listen on an alternate port, so I can interpose a software scheduler, written in python. The script I’m using to run the experiment is here:
https://github.com/amiller/library/blob/amiller-bug-oct15/run-bug.sh

But I’m encountering some unexpected behavior - the system stops making progress even after partitioning only 1 node. I’m wondering if you could help interpret the log files to understand what’s happening, or suggest how I could go about diagnosing it?

More details:
------
- I modified one line of code of BFT-SMaRt so that if a node is supposed to be reachable at port 100XX, then it actually listens on port 110XX (adds 1000). https://github.com/amiller/library/commit/e9bf11015d0c3456dd16a9960a18eb099694b1f5#diff-1fab8f649d6de8298fdf534e08c832c1R82
- Here is the python script that forwards from port 100XX to port 110XX, and can be scripted to create or heal partitions https://github.com/amiller/library/blob/amiller-bug-oct15/amiller-bug.py
  The scheduler can inspect the messages to determine when a view-change is about to occur.

Essentially I run the following experiments:
- Run 1: (OK) Ordinary (without any modified code)   Ordinary progress.  https://github.com/amiller/library/tree/amiller-bug-oct15/run1
- Run 2: (OK) Ordinary (with patched code, and python scheduler)  Same as previous. https://github.com/amiller/library/tree/amiller-bug-oct15/run2
- Run 3: (OK) After about 20 seconds, the scheduler isolates the leader (Node 0). As expected, a view-change occurs after 60 more seconds, and the system continues making progress. 
https://github.com/amiller/library/tree/amiller-bug-oct15/run3
-  Run 4: (OK) After about 20 seconds, the scheduler isolates the leader (Node 0). After the scheduler detects a view-change, the scheduler heals the partition. Progress continues as expected.
https://github.com/amiller/library/tree/amiller-bug-oct15/run4
-  Run 5. ***_(Fails!)_*** After about 20 seconds, the scheduler isolates the leader (Node 0) After the scheduler detects a view-change the scheduler delivers messages between Nodes {0,2,3}, but the would-be-new-Leader (Node 1) is isolated.
The system thereafter does not make any progress, but instead the nodes {0,2,3} continually attempt view-changes that do not succeed.
https://github.com/amiller/library/tree/amiller-bug-oct15/run5

**Comment by mikehearn** [comment]
@jcs47 how comes this issue was closed without comment? It sounds like a problem.

**Comment by jcs47** [comment]
This issue was discussed in emails with amiller, and it was already fixed in the latest release.

**Comment by amiller** [comment]
@jcs47 Hey, I thought I remembered such an email thread, but when I went to look, I couldn't find it. Could you remind me of some relevant search terms? Or even better, summarize what the problem and solution was here?

**Comment by jcs47** [comment]
Search for emails exchanged in November 2015 with the subject "bft-smart and viewchanges". The last email sent was by Prof. Bessani saying that the problem was fixed and commit to the repository.
