### ISSUE TITLE
Java 1.6 support

### ISSUE THREAD

**Issue by Kangmo** [bft-smart/library#28]
Hi guys, I am using bft-smart for my project and my customer is asking to support Java 6.
Do you have any plan to support Java 6? (Oracle extended the support of Java 6 until end of next year.)
If you are ok, I am going to create a pull request. The changes are all about specifying explicit types when you create an instance of a generic class.
```
     public BaseStateManager() {
-        senderStates = new HashMap<>();
-        senderViews = new HashMap<>();
-        senderRegencies = new HashMap<>();
-        senderLeaders = new HashMap<>();
-        senderProofs = new HashMap<>();
+        senderStates = new HashMap<Integer, ApplicationState>();
+        senderViews = new HashMap<Integer, View>();
+        senderRegencies = new HashMap<Integer, Integer>();
+        senderLeaders = new HashMap<Integer, Integer>();
+        senderProofs = new HashMap<Integer, CertifiedDecision>();
     }
```

**Comment by snakejerusalem** [comment]
Hello there. Unfortunately we have no plans to support java 6. I think the best course of action would be for you to create a fork of this repository where you can tweek the library for java 6. If you find some modification that impairs the library, let us know.

**Comment by Kangmo** [comment]
Hi snakejaerusalem, I got it. Thank you!
