### ISSUE TITLE
Bft smart dropping currentView in config directory no matter what

### ISSUE THREAD

**Issue by Raycoms** [bft-smart/library#32]
Bft smart should actually take the config home defined on startup of each replica and post the currentView there and not just in /config.

"  path = System.getProperty("user.dir") + sep + "config";"

There should be 2 constructors:

    public DefaultViewStorage(final String alternativePath) {
        String sep = System.getProperty("file.separator");
        path = System.getProperty("user.dir") + sep + alternativePath;
        File f = new File(path);
        if (!f.exists()) {
            f.mkdirs();
        }
        path = path + sep + "currentView";
    }

**Comment by jcs47** [comment]
Noted. I'll correct it soon.

**Comment by Raycoms** [comment]
If you add me to your repo I can create a pr with the changes I made to get it to drop it in the right directory.

**Comment by musalbas** [comment]
Addressed in pull request https://github.com/bft-smart/library/pull/43.
