### ISSUE TITLE
BFT Smart in crash mode leaderId = -1

### ISSUE THREAD

**Issue by Raycoms** [bft-smart/library#33]
Why does getLeader() on the primaryId of messageContext return -1 when reading it in the 2f+1 mode?

**Comment by jcs47** [comment]
I've tried to replicate the problem, but the getLeader() method worked as expected with me. Do you happen to be using that method when receiving an unordered message? If you do, that value is to be expected, given that the unordered messages are not submitted to the ordering protocol.

**Comment by Raycoms** [comment]
Ahh what a pity. Is there any way to get the leader without an ordered message?
