### ISSUE TITLE
Get confused by a true test in run_lc_protocol()

### ISSUE THREAD

**Issue by oldsharp** [bft-smart/library#38]
https://github.com/bft-smart/library/blob/master/src/bftsmart/tom/leaderchange/RequestsTimer.java#L162

```
if ((request.receptionTime + System.currentTimeMillis()) > t) {  // So this test will always be True, isn't it?
    pendingRequests.add(request);
}
```

What's the meaning of adding two time values with different unit?

**Comment by jcs47** [comment]
Yeah, that is definitely an error. It will be fixed soon.
