### ISSUE TITLE
Broken authentication? Insecure authkey for MAC creation

### ISSUE THREAD

**Issue by bergerch** [bft-smart/library#46]
In https://github.com/bft-smart/library/blob/master/src/bftsmart/communication/client/netty/NettyTOMMessageDecoder.java#L181 and https://github.com/bft-smart/library/blob/master/src/bftsmart/communication/client/netty/NettyClientServerCommunicationSystemClientSide.java#L199

The authkey is created from a string which is _clientID_:_replicaID_
However, since these IDs (and thus the authkeys) are known to any replica, a single malicious replica could spoof MACs and imitate  any other replica. By sending _n_ response TOMMessages, each of them with a spoofed _senderID_ and the respective correct MAC, the malicious replica can imitate all other replicas and thus "circumvent" the bft quorum and force the client to accept its result. 

I think it is necessary to use a key-agreement protocol for client-replica connections such as Diffie-Hellman to establish a secure shared secret, that no other system participant can know. Or perhaps did I overlook something here?

**Comment by jcs47** [comment]
You did not overlook anything. As it stands now, the MACs from the clients only provide protection agaisnt non-malicious Byzantine faults. But if you active the client signatures, you can obtain resilience to both malicious Byzantine faults and secure authentication for the clients.
