### ISSUE TITLE
getReplyQuorum() computed wrong in ServiceProxy?

### ISSUE THREAD

**Issue by bergerch** [bft-smart/library#48]
In https://github.com/bft-smart/library/blob/ff5f027ab7f110abc6f56900dc74f243cdf3107b/src/bftsmart/tom/ServiceProxy.java#L399:L406

The BFT quorum is computed by q = ceil((n+f)/2)+1 which should be wrong, because in a n=4 f=1 configuration this equals ceil((4+1)/2)+1 =ceil(2.5)+1 = 4
and not a single faulty replica can be tolerated!

This formula should use floor() instead of ceil() and should be used for input validation and not for output validation?

The CFT quorum is computed by q=ceil(n/2)+1 which should be wrong too, since in a n=3 f=1 config this equals ceil(3/2)+1 = 3 and not a single faulty replica can be tolerated!

Also: Shouldn't the correct quorum for **output validation** in BFT mode be f+1?  (thus 2 in a n=4 f=1 config) Because we can assume that at most f replicas are faulty?

In a CFT model, the quorum for **output validation** can be even constant 1? As replicas are only assumed to crash, if a response arrives at the client it must be correct?

I am seriously confused right now, so please explain if I am wrong because this error would lead to the BFT-SMaRt system's implementation not being fault tolerant at all.

**Comment by jcs47** [comment]
While it is true that the code for that method is confusing and should be re-written, you are forgetting a small but important detail: the division inside ceil() is done with Java integers, which means the result of that division is also an integer. Hence what is really happening is that for n=4 and f=1:

ceil((4+1)/2)+1 =ceil(2)+1 = 3

**Comment by bergerch** [comment]
Thank you for your fast reply! I overlooked the Java integers division. Also, I understand now why reply quorum can not be f+1 (because of read-only requests and concurrency)

**Comment by bergerch** [comment]
One last question: Why do you use the same reply quorum for ordered and read-only requests? Waiting for more than f+1 responses for an ordered request will unnecessarily increase the latency..

**Comment by jcs47** [comment]
True, but waiting for a quorum of replies is necessary when you enable the protocol to received both write and readonly requests. The only way to safely and correcly wait for only f+1 replies is to never use readonly requests.
