### ISSUE TITLE
TimeOut bft-smart multiple clients

### ISSUE THREAD

**Issue by Raycoms** [bft-smart/library#49]
I have a quite big number of clients, but after 1-2 minutes I get:

Client 41: 141 // 892 // TIMEOUT // Replies received: 3
Client 40: 140 // 892 // TIMEOUT // Replies received: 3
Client 42: 142 // 892 // TIMEOUT // Replies received: 3
Client 44: 144 // 896 // TIMEOUT // Replies received: 3
Client 38: 138 // 893 // TIMEOUT // Replies received: 3
Client 45: 145 // 895 // TIMEOUT // Replies received: 3

Now, I configured it to 4 replicas (bft) with f = 1.

I don't know what the issue is.

**Comment by Raycoms** [comment]
The main issue I see with this is that it does not seem to return to the invokation where I started it which  makes me unable to restart the commit or to mark it as an abort.

**Comment by jcs47** [comment]
I have no idea how to reproduce this problem without more information. Please, try to find a way to reproduce this bug within a *single machine* and with *a simple codebase*. Otherwise I simply have no clue about what its happening.

**Comment by Raycoms** [comment]
Unfortunately, this only happens when I turn on 8 replicas under extreme load.
(I run it on 4 machines).

What is very interesting to mention is that if I switch the replica ids it starts working for a bit again like:

Id 0: ip .1
id 1 ip.2
id 3 ip.3
id 4 ip.4
id 5 ip.5
id 6 ip.6
id 7 ip.7

After it stops working I can put it in reverse order (id 0-1 for Ip 7-1) and it will work a bit again until it starts causing problems again..

**Comment by Raycoms** [comment]
The load:

 I'm talking about 102+ clients sending messages to 3 bft-smart groups.
Occasionally, all clients might send it to the same group all together at the same time as well

**Comment by Raycoms** [comment]
Can you tell me at least where this happens, and what might be possible causes of this?

**Comment by jcs47** [comment]
Here it is what I don't understand: initially, you said you were using 4 replicas. Now you are saying that you are using 8. Does that happen with 4 or 8 replicas?

If you are indeed executing with 8 replicas, for some reason the clients are timing out after receiving only 3 replies. 3 replies are enough in a system of 4 replicas, but you would need 6 replies in a system with 8 if you are tolerating 2 faults from those 8 replicas (even if you want to tolerate just a single fault from those 8 replicas, clients would still need to gather 5 replies). For some reason, the clients simply do not received enough replies to proceed. Without more information, my best guess is that there is so much congestion in your network that the replies can't get to the clients in time. But the thing is, that timeout is hardcoded for 40 seconds...

**Comment by Raycoms** [comment]
I have 8 replicas, but they are organized in a manner so that in one bft-smart instance always 4 replicas are active. So out of the 4 replicas, the client gathers 3 replies and then it times out, shouldn't be three enough?

**Comment by jcs47** [comment]
Yes, in a system (or instance, as you call it) with 4 replicas, 3 replies are enough. But but for some reason, for as much as 40 seconds, you only get to receive 3 replies. Are you absolutely sure you have everything properly configured?

**Comment by Raycoms** [comment]
Yes, it works perfectly fine with less clients, only when I increase the
number of clients (+ add articifial latency) this happens.
But those 3 replies should satisfy the client, and he should return
already, no?

Why does he run into a timeout if he has 3 replies already?

I guess that for some reason a reply gets lost.

2017-11-06 21:24 GMT+00:00 jcs47 <notifications@github.com>:

**Comment by jcs47** [comment]
Do the following: go to config/system.config, at system.debug option, set it to 1. Launch your experiments again, and tell me what is the value of the following debug message: "Expected number of matching replies: "

**Comment by Raycoms** [comment]
The line with "expected number of matching replies has been "3".

**Comment by jcs47** [comment]
The output "Received n-f replies and no response could be extracted." indicates that, for some reason, the replies that are being gathered by the client aren't matching up to one another. You probably have some kind of non-determinism at server-side that doesn't generate matching replies amongst replicas. You have to audit the code you are using on the replicas. If you are supplying the client with your own comparator and/or extractor, I would also suggest you start looking into that too.

Additionally, you should also know that when a situation such as this one happens (n-f non-matching replies), the ServiceProxy object throws a Runntime Exception spawned from that situation. I remember that you already had problems with hidden exceptions some months ago, so I also suggest you try to find why the exception is not being displayed.

**Comment by Raycoms** [comment]
I'm fortunately not using custom comparators or extractors at the client,
but, the weird thing is that this bug only happens when I exaggerate
with the number of clients in an environment with latency (20ms between
each server - one way).
I can easily use 20 clients without any latency and this never happens. It
only appears when taking a high number of clients.

The problem with this is that I need this high number of clients so I can
saturate the database.

Is there anything I can do about this?

2017-11-07 20:35 GMT+00:00 jcs47 <notifications@github.com>:

**Comment by jcs47** [comment]
From what I can tell, the most likely explanation to this issue is that the database displays non-deterministic behaviour under heavy load. If this is indeed the case, then you have a significant obstacle to surpass, because the state machine replication paradigm needs the service to be completely deterministic.

But at this point, the best course of action for you to take is to find out what is causing the divergent replies. Start debuging and auditioning the code under heavy loads. The first step you should take is to had additional debug messages to bftsmart, so that you can see what is the content of each reply that is received. To compile the library after you had the extra output, you just need to type "ant" in the library folder.

**Comment by Raycoms** [comment]
Okay thanks, can you tell me where the message equality check happens? (In
which class)

2017-11-07 20:56 GMT+00:00 jcs47 <notifications@github.com>:

**Comment by jcs47** [comment]
The equality check happens here: https://github.com/bft-smart/library/blob/master/src/bftsmart/tom/ServiceProxy.java#L353

The code for the comparator is here:  https://github.com/bft-smart/library/blob/master/src/bftsmart/tom/ServiceProxy.java#L98

**Comment by Raycoms** [comment]
Client 31: [1, 99, 111, 109, 109, 105, 116, 47, 114, 101, 115, 112, 111, 110, 115, -27, 1, 99, 111, 109, 109, 105, -12, -4, -83, 1]
Client 31: [1, 99, 111, 109, 109, 105, 116, 47, 114, 101, 115, 112, 111, 110, 115, -27, 1, 99, 111, 109, 109, 105, -12, -6, -83, 1] 


Client 30: [1, 99, 111, 109, 109, 105, 116, 47, 114, 101, 115, 112, 111, 110, 115, -27, 1, 99, 111, 109, 109, 105, -12, -2, -83, 1] 
Client 30: [1, 99, 111, 109, 109, 105, 116, 47, 114, 101, 115, 112, 111, 110, 115, -27, 1, 99, 111, 109, 109, 105, -12, -128, -82, 1]

I am printing the arrays and it seems that some values are slightly off.
Nevertheless, I can't explain why this only happens when adding latency to the network and when adding a high amount of clients...

**Comment by jcs47** [comment]
You need to deserialize those arrays and see what results the replicas are sending for which commands. Even if you can't figure out how to prevent that non-deterministic behaviour, at least you can discover what operations to avoid when performing experimental evaluations.

**Comment by Raycoms** [comment]
Hi there, this seems to be happening a lot. I tried to add my own custom comparator:

`new Comparator<byte[]>()
        {
            @Override
            public int compare(byte[] o1, byte[] o2)
            {
                if (Arrays.equals(o1, o2))
                {
                    return 0;
                }

                final Kryo kryo = new Kryo();
                try (final Input input1 = new Input(o1); final Input input2 = new Input(o2))
                {
                    final String messageType1 = kryo.readObject(input1, String.class);
                    final String messageType2 = kryo.readObject(input2, String.class);

                    if (!messageType1.equals(messageType2))
                    {
                        System.out.println("Message types differ: " + messageType1 + " : " + messageType2);
                        return -1;
                    }

                    if (messageType1.equals(Constants.COMMIT_RESPONSE))
                    {
                        final String commit1 = kryo.readObject(input1, String.class);
                        final String commit2 = kryo.readObject(input1, String.class);

                        if (!commit1.equals(commit2))
                        {
                            System.out.println("Commit responses differ: " + commit1 + " : " + commit2);
                            return -1;
                        }
                    }
                    else
                    {
                        System.out.println("Something went wrong, those messages are no commit responses: " + messageType1);
                    }
                }
                catch (final Exception e)
                {
                    System.out.println("Something went wrong deserializing:" + e.getMessage());
                    return -1;
                }

                return 0;
            }
        }`

Nevertheless, whatever I do, this custom comparator is not being used, I tried adding it as the comparator in the constructor and I tried creating a "setComparator" method, both ways did not try.

The custom comparator is not being executed (I tested that by always returning 0 no matter what).

**Comment by jcs47** [comment]
Which class are you using to instantiate the clients, and how are you passing the comparator?

**Comment by Raycoms** [comment]
public class TestClient extends ServiceProxy implements BAGClient,
ReplyReceiver, Closeable, AutoCloseable


super(processId, localClusterId == -1 ? GLOBAL_CONFIG_LOCATION :
String.format(LOCAL_CONFIG_LOCATION, localClusterId), new
Comparator<byte[]>()
{
    @Override
    public int compare(byte[] o1, byte[] o2)
    {
        if (Arrays.equals(o1, o2))
        {
            return 0;
        }

        final Kryo kryo = new Kryo();
        try (final Input input1 = new Input(o1); final Input input2 =
new Input(o2))
        {
            final String messageType1 = kryo.readObject(input1, String.class);
            final String messageType2 = kryo.readObject(input2, String.class);

            if (!messageType1.equals(messageType2))
            {
                System.out.println("Message types differ: " +
messageType1 + " : " + messageType2);
                return -1;
            }

            if (messageType1.equals(Constants.COMMIT_RESPONSE))
            {
                final String commit1 = kryo.readObject(input1, String.class);
                final String commit2 = kryo.readObject(input1, String.class);

                if (!commit1.equals(commit2))
                {
                    System.out.println("Commit responses differ: " +
commit1 + " : " + commit2);
                    return -1;
                }
            }
            else
            {
                System.out.println("Something went wrong, those
messages are no commit responses: " + messageType1);
            }
        }
        catch (final Exception e)
        {
            System.out.println("Something went wrong deserializing:" +
e.getMessage());
            return -1;
        }

        return 0;
    }
}, null);


2017-11-23 23:29 GMT+00:00 jcs47 <notifications@github.com>:

**Comment by Raycoms** [comment]
```public class TestClient extends ServiceProxy implements BAGClient,
ReplyReceiver, Closeable, AutoCloseable


super(processId, localClusterId == -1 ? GLOBAL_CONFIG_LOCATION :
String.format(LOCAL_CONFIG_LOCATION, localClusterId), new
Comparator<byte[]>()
{
    @Override
    public int compare(byte[] o1, byte[] o2)
    {
        if (Arrays.equals(o1, o2))
        {
            return 0;
        }

        final Kryo kryo = new Kryo();
        try (final Input input1 = new Input(o1); final Input input2 =
new Input(o2))
        {
            final String messageType1 = kryo.readObject(input1, String.class);
            final String messageType2 = kryo.readObject(input2, String.class);

            if (!messageType1.equals(messageType2))
            {
                System.out.println("Message types differ: " +
messageType1 + " : " + messageType2);
                return -1;
            }

            if (messageType1.equals(Constants.COMMIT_RESPONSE))
            {
                final String commit1 = kryo.readObject(input1, String.class);
                final String commit2 = kryo.readObject(input1, String.class);

                if (!commit1.equals(commit2))
                {
                    System.out.println("Commit responses differ: " +
commit1 + " : " + commit2);
                    return -1;
                }
            }
            else
            {
                System.out.println("Something went wrong, those
messages are no commit responses: " + messageType1);
            }
        }
        catch (final Exception e)
        {
            System.out.println("Something went wrong deserializing:" +
e.getMessage());
            return -1;
        }

        return 0;
    }
}, null);
```

**Comment by jcs47** [comment]
I noticed you are implementing the `ReplyReceiver` interface, which is already implemented by the `ServiceProxy` (through the `TomSender` class). This is important because in the `ServiceProxy`, the comparator is used in the `replyReceived()` method, which belongs to `ReplyReceiver`. Do you happen to be re-implementing that method?

**Comment by Raycoms** [comment]
Yes but only for analytical purposes I always call super. Still the
comparator should be used.

On Nov 23, 2017 22:21, "jcs47" <notifications@github.com> wrote:

I noticed you are implementing the ReplyReceiver interface, which is
already implemented by the ServiceProxy (through the TomSender class). This
is important because in the ServiceProxy, the comparator is used in the
replyReceived() method, which belongs to ReplyReceiver. Do you happen to be
re-implementing that method?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bft-smart/library/issues/49#issuecomment-346712104>,
or mute
the thread

**Comment by jcs47** [comment]
I just tested it myself, and with me the custom comparator is indeed used. Please check out again your code to see if you are not overriding anything.

**Comment by jcs47** [comment]
Try re-working your code to avoid extending ServiceProxy and implementing ReplyReceiver. Just use a ServiceProxy object as an attribute of your TestClient class instead of making that class a sub-class of ServiceProxy.

**Comment by Raycoms** [comment]
How will I get then the result of this: localProxy.sendMessageToTargets(this
.serialize(Constants.READ_MESSAGE, timeStampToSend, identifier), 0, 0, new
int[] {serverProcess}, TOMMessageType.UNORDERED_REQUEST)

I use replyReceived to get the result of a single message send.

2017-12-05 17:25 GMT+00:00 jcs47 <notifications@github.com>:

**Comment by jcs47** [comment]
You can use the AsyncServiceProxy class together with the ReplyListener interface (*Listener*, not *Receiver*)

**Comment by Raycoms** [comment]
Adapted it like that: https://github.com/Raycoms/fireplug/blob/working/src/main/java/main/java/com/bag/client/TestClient.java#L102

But for some reason I don't get the replies at all.

**Comment by Raycoms** [comment]
Any idea?

**Comment by jcs47** [comment]
You should not use `sendMessageToTargets` anymore because you are not giving out any `ReplyListener` into your `AsyncServiceProxy`. Don't make `TestClient` extend `ReplyListener`, make a separate class that extends `ReplyListener` and pass an instance of that class into your `AsyncServiceProxy` using the `invokeAsynchRequest` method.

**Comment by Raycoms** [comment]
@jcs47 Okay, I finally got it working, and I found out that the issue seems to be bitflips.
In 90% of the messages they run through perfectly well, but for 10% of them they fail.
For those 10% I deserialize it and check the content, which until now worked in 100% of the cases.

**Comment by jcs47** [comment]
Victory!

 ![Victory](https://4.bp.blogspot.com/-Sbau5QlY70Y/WRt_L-YELTI/AAAAAAAAIvI/yZ-AKsO1QXwcsBLeCr5AKtATV5UFuFJiwCLcB/s1600/anchorman%2Bgif.gif)
