### ISSUE TITLE
[BUG] Messages to multiple targets

### ISSUE THREAD

**Issue by bergerch** [bft-smart/library#50]
While building a Forwarder with BFT-SMaRt, I encountered a severe bug that occurs when sending a single message to multiple targets:

https://github.com/bft-smart/library/blob/6892ab38135a222a2cf5d54fbbd5c586ec0aef6f/src/bftsmart/communication/client/netty/NettyClientServerCommunicationSystemServerSide.java#L274:L283

The bug is here:
```
for (int i = 0; i < targets.length; i++) {
			rl.readLock().lock();
			//sendLock.lock();
			try {       
				NettyClientServerSession ncss = (NettyClientServerSession) sessionTable.get(targets[i]);
				if (ncss != null) {
					Channel session = ncss.getChannel();
					sm.destination = targets[i];
					//send message
session.writeAndFlush(sm);
```
**Problem:**
writeAndFlush() works asynchronously, so you can not assume that the messages have been already sent when the _for loop_ goes to the next iteration. But in the next iteration the _destination_ field of the same object (sm) is being modified and since the objects are passed by reference in Java, the destination field will have the same value (target[1] instead of target[0]) for both iterations, which leads to them being encoded in exactly the same way: with the same MACs being applied to them although they are being sent to different clients. This leads to one client rejecting the message because it thinks that the MAC is corrupt. 

**Solution:**
It is sufficient to make a shallow copy and pass the copied object to writeAndFlush()

**Comment by jcs47** [comment]
Thank you, I'll fix it in an upcoming commit.
