### ISSUE TITLE
Denial of Service and Timeout Manipulation possible?

### ISSUE THREAD

**Issue by bergerch** [bft-smart/library#51]
Attacks that impact message delay such as denial of service attacks can be used to increase the timeout value used to detect a faulty leader e.g. in such an attacking scenario the timeouts doubles each time the view changes. The adversary can use this behavior by stopping its attack when a malicious replica is the leader, thus the malicious leader can slow down the system's throughput dramatically. [1]

**My question is:**
Is the request timer in BFT-SMaRt increased (e.g. doubled) when the leader changes and if so, is it being reset later on? (So basically would a timeout manipulation attack be possible?)

[1] compare Amir, Yair, et al. "Prime: Byzantine replication under attack." IEEE Transactions on Dependable and Secure Computing 8.4 (2011): 564-577.

**Comment by jcs47** [comment]
As you pointed out in your second post, the library is not doubling its timeout anymore after a regency change. We decided to go for the alternate take on eventually synchronous systems where time bounds are indeed known, but may not be guaranteed to hold, at least until some given instant in the system's lifespan.

However, even though timeout manipulation cannot be done by malicious clients, it is still possible to perform a DDoS attack akin to what Amir et al, described. If there are enough malicious clients in the system submitting requests, the set of unordered requests maintained by each replica may grow at a larger rate than the rate at which the system is able to establish a total order for those requests. This can result in timeouts associated to those unordered requests, does spawning new regency changes that can hand the role of leader to a Byzantine replica.

**Comment by bergerch** [comment]
Thank you for your detailed reply!
