### ISSUE TITLE
Reproducing performance results

### ISSUE THREAD

**Issue by Helios-vmg** [bft-smart/library#52]
Hi, I'm trying to reproduce the results described in [the paper](http://repositorio.ul.pt/bitstream/10455/6897/1/TR-2013-07.pdf) using the ThroughputLatency microbenchmark, but I can't get any more than ~20 ops/s, which is nowhere near the ~70 kops/s mentioned in it. The paper describes a setup where each replica is running on its own Xeon machine, while mine are all running on the same VM, but I have a hard time believing that could be the problem when the CPU is mostly idling. Can you think of what could be causing this discrepancy?

**Comment by jcs47** [comment]
How  are you trying to reproduce the results? Are you using one of the microbenchmarks provided with the library or did you set up your own code?

**Comment by Helios-vmg** [comment]
Yes, sorry, I thought I had mentioned it. I am using the microbenchmark.

**Comment by jcs47** [comment]
Ok, could you then show the parameters you use both at the clients and replicas to launch it? Also, did you by any chance activated digital signatures?

**Comment by Helios-vmg** [comment]
Server: 
./runscripts/smartrun.sh bftsmart.demo.microbenchmarks.ThroughputLatencyServer $SERVER_NUMBER 50 100 100 1

Client:
./runscripts/smartrun.sh bftsmart.demo.microbenchmarks.ThroughputLatencyClient 1001 1 70000 100 50 0 0

**Comment by jcs47** [comment]
You are using an interval of 50 ms in the client. This means you are making the client wait 50 ms before issuing the next request, plus the latency associated with waiting for a quorum of replies from the servers. All experimental evaluations presented in the paper were done using 0 miiseconds, thus the only delay between requests is the latency associated with the aforementioned replies.

I would also suggested you use a larger interval at the server (parameter that comes next to $SERVER_NUMBER) once you start getting larger throughput values. Notice that the interval parameter in the server does not mean the same as it does in the client: while the client uses that parameter to insert a delay between requests, in the server this is used as the number of operations to received before calculating and outputing more throughput results.

**Comment by Helios-vmg** [comment]
Well, that does help, but I'm still only at ~900 ops/s. I am running all servers on the same VM, but is that really enough to cut down performance by ~70 times?

**Comment by jcs47** [comment]
Bear in mind you are using a single client thread and a single JVM instance. Even if you were using a distributed deployment, you would need considerable more clients than that.

Try using something like this:

./runscripts/smartrun.sh bftsmart.demo.microbenchmarks.ThroughputLatencyClient 1001 50 70000 100 0 false false (JVM A)

./runscripts/smartrun.sh bftsmart.demo.microbenchmarks.ThroughputLatencyClient 2001 50 70000 100 0 false false (JVM B)

**Comment by Helios-vmg** [comment]
Ah, I missed that part. Yeah, running that many processes would be kind of a tall order.
Alright, thanks.

**Comment by bruceshao** [comment]
@Helios-vmg  can u tell me your tps?
Now I use 4 clients send message, and they are all in a total machine,but my max result is 10000 ops/sec......

**Comment by Helios-vmg** [comment]
@bruceshao Sorry, this was just a quick experiment I ran last year, and I haven't touched this since. At this point the information I've posted in this thread is all I have, unfortunately.

**Comment by bruceshao** [comment]
@Helios-vmg Thanks anyway~ I have found the reason. As you mentioned in issue, adding client can increase TPS in the case of multiple servers.
