### ISSUE TITLE
does bft-smart have been used in production enviroment?

### ISSUE THREAD

**Issue by young001** [bft-smart/library#54]
does bft-smart have been used in production enviroment?
which project use bft-smart?

thx

**Comment by jcs47** [comment]
We know that the developers of Symbiont Assembly ported BFT-SMaRt to Go and use it as their total order protocol. We also know that the Corda platform  released a version that provides a BFT distributed notary based on BFT-SMaRt. But other than these projects, we aren't aware of any other usage of the library in production environment.

**Comment by young001** [comment]
gotcha,thx
