### ISSUE TITLE
BftSmart, extract additional information

### ISSUE THREAD

**Issue by Raycoms** [bft-smart/library#55]
Hi,

I'm running bft smart in a bigger environment and I would like to send to other servers a proof of the order process.
Since the bftSmart nodes interact to define a order, each server probably has to sign its decision and send it to the others.
Is there a way to obtain these signatures at one of the replicas?

    public byte[][] appExecuteBatch(final byte[][] bytes, final MessageContext[] messageContexts, final boolean noop)

It would be great for example if we could find these signatures in the messageContext.

**Comment by jcs47** [comment]
Use the getProof() method from the MessageContext object. It gives you a set of ACCEPT messages that each contain a MAC vector from 2f+1 replicas.

**Comment by Raycoms** [comment]
Ah great =) Thanks a lot

2018-03-22 15:53 GMT+00:00 jcs47 <notifications@github.com>:

**Comment by Raycoms** [comment]
How do I check if the signatures match?
