### ISSUE TITLE
BftSmart not ordering well when too many requests come in.

### ISSUE THREAD

**Issue by Raycoms** [bft-smart/library#56]
I noticed that the order of the requests in executeBatch can vary depending on the amount of client requests.

I noticed that the sequence ID and the consensus ID seem well, but the array of the messages is out of order.

Meaning I can't just

```
    @Override
    public byte[][] appExecuteBatch(final byte[][] bytes, final MessageContext[] messageContexts, final boolean noop)
    {

final byte[][] allResults = new byte[bytes.length][];
        for (int i = 0; i < bytes.length; ++i)
        {

        consume(bytes[i)];
```

Execute them like this, because they are not guaranteed in the right order

**Comment by jcs47** [comment]
What do you mean by being out of order? Are you saying that each replica receives messages by different order, or that FIFO order in respect to each client is not guaranteed? Please be more precise.

**Comment by Raycoms** [comment]
I'm currently debugging this, is it possible that appExecuteBatch gets
called concurrently for each batch?

2018-03-30 19:36 GMT+01:00 jcs47 <notifications@github.com>:

**Comment by jcs47** [comment]
No

**Comment by Raycoms** [comment]
So the next batch only gets called after I returned the response for the current batch, right?

**Comment by jcs47** [comment]
Exactly. But bear in mind, you can get batches of different _sizes_ across different replicas. However, the order by which the messages are ordered should be the same.

**Comment by Raycoms** [comment]
I'm currently debugging this, and it's incredibly strange, All replicas receive the same data until a certain moment, then, out of nothing, 1 replica starts getting completely different data than the other 3

**Comment by jcs47** [comment]
Which replica? Maybe what you are seeing is a replica getting late in relation to all others. This is a common phenomenom. Try to halt all clients and allow all replica to finish processing.

**Comment by Raycoms** [comment]
It is each time another replica, it seems like all messages arrive in order, but 1 of the messages isn't getting executed for some reason.

**Comment by jcs47** [comment]
Like I said, check if what you are seeing is a delayed replica.

**Comment by Raycoms** [comment]
I found it... Somewhere the code was going down, for some reason I didn't get an exception again and this stopped the execution of the next message in the batch.
