### ISSUE TITLE
Where is BFTMap?

### ISSUE THREAD

**Issue by maxim-levy** [bft-smart/library#59]
It seems like some tests (`test/bftsmart/demo/bftmapjunit/ConsoleTest.java` for example) are using `BFTMap`, but I can't find the code for this - only the class module is present: `/bin/bftsmart/demo/bftmap/BFTMap.class`. Is that by design?

**Comment by jcs47** [comment]
Hi there. The demo is back in the master branch under the bftsmart.demo.map package. Some methods are still not implemented, but they will be eventually.
