### ISSUE TITLE
Insecure leader selection at state transfer

### ISSUE THREAD

**Issue by azuenko** [bft-smart/library#62]
I've spotted somewhat strange way of leader selection at state trasfer.

In [StandartStateManager.java](https://github.com/bft-smart/library/blob/ff07a6797fd0fa00aed5d5f71f0ba639a883660b/src/bftsmart/statemanagement/strategy/StandardStateManager.java#L184) a new leader is selected once enough state manager replies received:
```java
    if (enoughLeaders(msg.getLeader())) currentLeader = msg.getLeader();
```
The actual implementation of `enoughLeaders` in [BaseStateManager.java](https://github.com/bft-smart/library/blob/ff07a6797fd0fa00aed5d5f71f0ba639a883660b/src/bftsmart/statemanagement/strategy/BaseStateManager.java#L82-L84):
```java
    protected boolean enoughLeaders(int leader) {
        return senderLeaders.size() > SVController.getQuorum();
    }
```

What I find weird is the following:
* No check is done to make sure that **the same** leader is reported by the quorum, only the messages are counted
* New leader id is picked from the last received message, the one that triggers the condition comparing message counter to the quorum
* Dangling `int leader` argument in `enoughLeaders`

The same arguments also apply to `enoughRegencies`. 

I believe that the functions should be implemented similar to [enoughViews](https://github.com/bft-smart/library/blob/ff07a6797fd0fa00aed5d5f71f0ba639a883660b/src/bftsmart/statemanagement/strategy/BaseStateManager.java#L86-L96):
```java
    protected boolean enoughViews(View view) {
        Collection<View> views = senderViews.values();
        int counter = 0;
        for (View v : views) {
            if (view.equals(v)) {
                counter++;
            }
        }
        boolean result = counter > SVController.getQuorum();
        return result;
    }
```

Can anyone confirm the bug, please?

**Comment by azuenko** [comment]
It could be that an attacker is capable to become the leader at fist and any subsequent leader change, preventing the liveness of the system.

**Comment by jcs47** [comment]
This definitely looks like a dumb mistake. I'll check it out soon.
