### ISSUE TITLE
Replay attack due to unsynchronized lastMessageReceived

### ISSUE THREAD

**Issue by azuenko** [bft-smart/library#63]
According to [the paper](https://dl.acm.org/citation.cfm?id=2310272&preflayout=flat),

> Requests are only considered by correct replicas if the message contains a valid signature and the sequence number expected from this client (to avoid replay attacks), as checked in line 21

The sequence numbers are [checked](https://github.com/bft-smart/library/blob/ff07a6797fd0fa00aed5d5f71f0ba639a883660b/src/bftsmart/clientsmanagement/ClientsManager.java#L262-L264) by servers upon reception. The check compares the sequence number  with `lastMessageReceived` variable in [ClientData.java](https://github.com/bft-smart/library/blob/ff07a6797fd0fa00aed5d5f71f0ba639a883660b/src/bftsmart/clientsmanagement/ClientData.java#L38). Clients are supposed to increment the sequence number for each new request within the same session. The same message with the same session ID and sequence number received twice is considered as a duplicate (or replay attack) and not processed.

However, last sequence numbers per client/session are never synchronised neither through messages, nor through the log.

Here's the demonstration of the replay attack. It only requires minor modification of client code and waiting till enough servers crash at least one.

1. Fix session ID to a constant value: replace [this line](https://github.com/bft-smart/library/blob/ff07a6797fd0fa00aed5d5f71f0ba639a883660b/src/bftsmart/tom/TOMSender.java#L91) with `this.session = 42;` 
2. Run demo counter example with 4 servers:
```
./runscripts/smartrun.sh bftsmart.demo.counter.CounterServer 0
./runscripts/smartrun.sh bftsmart.demo.counter.CounterServer 1
./runscripts/smartrun.sh bftsmart.demo.counter.CounterServer 2
./runscripts/smartrun.sh bftsmart.demo.counter.CounterServer 3
```
3. Run counter client to increase the value from 0 to 10. The command would succeed:
```
./runscripts/smartrun.sh bftsmart.demo.counter.CounterClient 1001 10 1
```

4. Run the previous command once again. It would fail, since the same request (session id = 42, request id = 0) would be sent twice. This is how the system should react. 

5. Restart each server process subsequently. After synchronisation they would catch up the log, but not the last sequence ID.

6. Repeat the client command in step 3. It would now succeed, and the counter would be increased to 20. It is possible since none of the servers knows that the request from client 1001 with session id 42 and request id 0 has been already handled. 

The attack can be mounted even if the channel client-server is encrypted by lower protocol (like TLS). In this case if the attacker have control over one of the servers, he could save an entire session (requests from 0 to N) and then replay it once enough servers are restarted.

**Comment by jcs47** [comment]
Good catch. This would not be a big problem under the strict fail-stop model (which is what the paper assumes), but since we allow replicas to recover, this case must be accounted for. I will had this to the TODO list. Thanks for letting us know.

**Comment by azuenko** [comment]
Thank for the acknowledging. If you permit, I can share some thoughts about it.

If we want to prevent replay attacks, not only the `lastMessageReceived` should be synchronized, but also session IDs for all requests in the past. For instance, a request with session id `5836`, and sequence id `0` is received. Let's say it's a replay attack, and the original request was sent 6 months ago. To reject it, all nodes should be aware of the fact that the request had been processed, i.e. they should store and synchronize its identifier: `5386/0`. To do so, they should keep all processed identifiers. 

And even if with `lastMessageReceived` we don't have to keep all the integers but only the last one, session IDs, being random, should be kept entirely since the beginning. Using a hash table it's possible to do fast lookups, but there's no deterministic algorithm to make the storage of session IDs space-efficient. It's, however, possible to use probabilistic approach, such as bloom filter. The downside would be the retransmission of the request with new identifier if its falsely classified as a replay attack. 

Another approach would be to not to keep all identifiers, but only the last `N`. If a request's identifier is found in that list, it's immediately rejected as replay attack. If it's not found, then the request's timestamp is checked. If the timestamp is within the range of server's timestamp ± `delta`, it's processed, otherwise it's considered as replay attack and rejected. `delta` should be big enough to tolerate the clock skew, but not too big. `N` should be "larger" that `delta` to avoid the gap: the replay attack can still be processed because it's timestamp is still within the range, and can be processed, because its identifier has been purged from the list of processed identifiers. Informally, `clock skew < delta < N < memory available`

If the wall clock cannot be used synchronize client and server, they can use log height (consensus ID) for the same purpose. Since the client does not know a priori the current log height, it has to learn it through a communication round with one or quorum of servers. Then the client puts the last known consensus ID into its request, which is used by the server the similar way as timestamp : to distinguish new requests from old ones. In this case the setting of values of `N` and `delta` is simplified, as it does not depend anymore on the request processing speed. We may simply say that each log entry is associated with the request identifier, we keep last `N` identifiers, and we put `delta = N`, meaning that we process request only if its last known height within the range `[consensusID - N; consensusID]` and the request identifier is not found in the list of processed ones. The downside of the approach is the additional implementation of the client-server synchronization.

I would appreciate any feedback, it'll be very helpful.
