### ISSUE TITLE
Trying to run a Yahoo! Cloud Serving Benchmark

### ISSUE THREAD

**Issue by george321** [bft-smart/library#64]
i run 
`./runscripts/startReplicaYCSB.sh 0
./runscripts/startReplicaYCSB.sh 1
./runscripts/startReplicaYCSB.sh 2
./runscripts/startReplicaYCSB.sh 3`

Then i run:
`./runscripts/ycsbClient.sh`

and in all servers i get

> gmitaros@ubuntu:~/library$ ./runscripts/startReplicaYCSB.sh 3-- Using view stored on disk

> -- Diffie-Hellman complete with 0
> -- Diffie-Hellman complete with 1
> -- Diffie-Hellman complete with 2
> -- ID = 3
> -- N = 4
> -- F = 1
> -- Port = 11030
> -- requestTimeout = 2000
> -- maxBatch = 400
> -- Using MACs
> -- In current view: ID:0; F:1; Processes:0(/127.0.0.1:11000),1(/127.0.0.1:11010),2(/127.0.0.1:11020),3(/127.0.0.1:11030),
> -- Retrieving State
> getState called
> -- Replica state is up to date
> -- Ready to process operations
> Session Created, active clients=0
> Session Created, active clients=0
> Session Created, active clients=0
> Session Created, active clients=3
> Session Created, active clients=4
> Session Created, active clients=5
> Session Created, active clients=5
> Session Created, active clients=7
> Exception in thread "Delivery Thread" java.lang.NoClassDefFoundError: bftsmart/tom/ServiceReplica$3
> 	at bftsmart.tom.ServiceReplica.receiveMessages(ServiceReplica.java:299)
> 	at bftsmart.tom.core.DeliveryThread.deliverMessages(DeliveryThread.java:294)
> 	at bftsmart.tom.core.DeliveryThread.run(DeliveryThread.java:225)
> Caused by: java.lang.ClassNotFoundException: bftsmart.tom.ServiceReplica$3
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 

> 	... 3 more
> Session Created, active clients=8
> Session Created, active clients=9

**Comment by jcs47** [comment]
Sorry for the late reply, I've been traveling this past week.

I tried to reproduce the error using the same commands you used, but everything works as expected in my end. Have you changed anything else? Does this also happen with other demos such as the counter client?
