### ISSUE TITLE
FAQ unsertainy: The bft-smart protocol should work with at least 3f+1 replicas, not 3f-1 replicas

### ISSUE THREAD

**Issue by zhaohaidao** [bft-smart/library#65]
**Question**
How many replicas do I need to keep my service working
**Current Answer**
The BFT-SMaRt protocol works with the assumption that the system is comprised by at least **3f-1** replicas
**My Understanding**
The system should be comprised by at least **3f+1** replicas, not 3f-1 replicas
**References**
https://github.com/bft-smart/library/wiki/FAQ
https://github.com/bft-smart/library/wiki/How-BFT-SMaRt-works

**Comment by jcs47** [comment]
Yes, that was a mistake. Fixed!
