### ISSUE TITLE
Incorrect Rounding Behavior in Quorum Calculation

### ISSUE THREAD

**Issue by jasonkresch** [bft-smart/library#68]
In ServerViewController.java line numbers 302 and 303:

			this.quorumBFT = (int) Math.ceil((this.currentView.getN() + this.currentView.getF()) / 2);
			this.quorumCFT = (int) Math.ceil(this.currentView.getN() / 2);

There is a call to Math.ceil(), with the intention of rounding up when N+F is odd.  However, this function is applied to the result of an integer division which always rounds down.  This results in underestimating the quorum size for certain combinations of N and F.  For example:

N = 4, F = 1, quorumBFT = 2, but it should be 3
N = 7, F = 2, quorumBFT = 4, but it should be 5

A simple fix would be to change "2" in the above to "2.0" or "2F" which will result in a floating point rather than an integer division.

**Comment by jcs47** [comment]
That is because the convention we use in the codebase is to use `>` rather than `>=` to verify if a quorum is reached:

```
Usages of ServerViewController.getQuorum [9 occurrences]
BFT-SMaRt
ExecutionManager.java
  428:  return (countAccepts > controller.getQuorum());
BaseStateManager.java
    91:  boolean result = counter > SVController.getQuorum();
  104:  boolean result = counter > SVController.getQuorum();
  117:  boolean result = counter > SVController.getQuorum();
  155:  boolean result = counter > SVController.getQuorum();
  259:  if (senderCIDs.size() >= SVController.getQuorum()) {
  274:  if (cids.get(key) >= SVController.getQuorum()) {
Acceptor.java
  270:  if (writeAccepted > controller.getQuorum() && Arrays.equals(value, epoch.propValueHash)) {
  410:  if (epoch.countAccept(value) > controller.getQuorum() && !epoch.getConsensus().isDecided()) {
```

**Comment by jasonkresch** [comment]
Ahh I see, that explains it and appears to be correct.  I would say however that the use of Math.ceiling then is misleading and a no-op.  In effect, "quorumBFT" is computed as: (N+F)>>1.

Are lines 259 and 274 correct? I see they are using ">=".  Thanks for your help in this matter.

**Comment by jcs47** [comment]
> Ahh I see, that explains it and appears to be correct. I would say however that the use of Math.ceiling then is misleading and a no-op. In effect, "quorumBFT" is computed as: (N+F)>>1.

Indeed!

> Are lines 259 and 274 correct? I see they are using ">=". Thanks for your help in this matter.

That has also come to my attention when I shared the usages of getQuorum(). I've looked into that part of the code, and it is in fact a little bit messy. It is a part of the code that deals with the initial phase of state transfer, when replicas that have been started try to discover if they have recovered by finding if the other replicas were already processing requests. I'll will work on it.

**Comment by jcs47** [comment]
That section of the code is patched up now, feel free to pull the latest updated:

```
Usages of ServerViewController.getQuorum [9 occurrences]
BFT-SMaRt
BaseStateManager.java
    94:  boolean result = counter > SVController.getQuorum();
  107:  boolean result = counter > SVController.getQuorum();
  120:  boolean result = counter > SVController.getQuorum();
  158:  boolean result = counter > SVController.getQuorum();
  288:  if (replies.size() > SVController.getQuorum()) {
  308:  if (cids.get(cid) > SVController.getQuorum()) {
ExecutionManager.java
  428:  return (countAccepts > controller.getQuorum());
Acceptor.java
  270:  if (writeAccepted > controller.getQuorum() && Arrays.equals(value, epoch.propValueHash)) {
  410:  if (epoch.countAccept(value) > controller.getQuorum() && !epoch.getConsensus().isDecided()) {
```
