### ISSUE TITLE
What experiment environment can make Throughput 80000+ ？

### ISSUE THREAD

**Issue by bruceshao** [bft-smart/library#72]
My Blockchain use bft-smart to consensus(order). I found it can make Throughput 80000+ from paper, but I can just get 12000+ (4 servers) , Please help~

**Comment by jcs47** [comment]
You said you are using the library in a blockchain system, so I reckon you are performing disk writes and creating/verifying digital signatures. But the results in the paper were conducted without any of that (everything in memory and with MAC vectors). Disk access and digital signatures are well known for their performance overhead. In fact, a throughput of 12000 txx/sec is within the ballpark of the experiments we have also been doing recently with a blockchain system of our own. Furthermore, keep in mind that the 80 000 reqs/sec result were obtained with a payload of 0 bytes both for the requests and replies.

**Comment by bruceshao** [comment]
I have referred to the previous issue and found that it was my own environment that caused it. 
The TPS of my MAC can only reach 12000+ (no matter how many clients I use).
However, in the case of 800Clients with several physical machines, TPS >= 50000+.
Although not completely experimental results, but basically near it.
thx...
