### ISSUE TITLE
Triggering state transfers on byzantine faults?

### ISSUE THREAD

**Issue by codyscode** [bft-smart/library#73]
I'm working on a filesystem that uses bft-smart. If I simulate a crash by stopping a replica then bringing it back online the state transfer is successfully triggered. However, if I simulate a byzantine fault by deleting a file from one of the replicas while it's still running then try to access that file from the client, I see the file is still being served and the fault is being tolerated, but a state transfer is never triggered. I've tried various settings in system.config but as I dig deeper it seems like maybe this isn't a feature of the protocol?

**Comment by sdlyyxy** [comment]
Hi, @codyscode , did you solve this problem?
