### ISSUE TITLE
Can't run smartrun.sh

### ISSUE THREAD

**Issue by ehsun786** [bft-smart/library#83]
Hi,

I am unable to run the Counter example. I am attempting to run the Counter Demo but it isn't working. The response I get is given below. I have also given an attachment to my host file.
![Capture](https://user-images.githubusercontent.com/16247138/85898169-b5028a80-b7f3-11ea-9725-e4e72c91adea.PNG)

$ runscripts/smartrun.sh bftsmart.demo.counter.CounterServer 0
Error: Could not find or load main class bftsmart.demo.counter.CounterServer

Can you please help me with this. Thankyou.

**Comment by yanchovy** [comment]
Hello, I have exactly the same issue and it seems I'm unable to resolve it. Could you please help? Thanks

**Comment by yanchovy** [comment]
Thank you for your response. Actually for me it seems that smartrun.sh is located in the runscripts folder and I just cloned the repo today.

**Comment by rvassantlal** [comment]
Have you compiled the code following the instructions presented [here](https://github.com/bft-smart/library#compiling)?

**Comment by yanchovy** [comment]
Alright, I compiled the code now as it has been said in the readme file, but I still get the same issue

**Comment by rvassantlal** [comment]
From where are you running the code? It should be from within build/install/library folder.

**Comment by yanchovy** [comment]
Oh okay I was running it from a different place. Thank you!
