### ISSUE TITLE
Number of servers

### ISSUE THREAD

**Issue by dgiantsidi** [bft-smart/library#86]
Hi all,

Is it possible to run 5 replicas and handle 1 failure? Given that there need to be at least 3f+1 replicas, which in our case, equals to 4, I assume that it is ok to set the servers.num = 5 to the config.host.

However, the system ignores completely this parameter and "starts" when the 4 replicas complete their handshakes ignoring completely the 5th replica (that replica also reports "not in the current view" -- I delete the currentView file)

Could you please help me on that?

Thanks,
Dimitra

**Comment by shenlinxian** [comment]
You need to change system.initial.view in config.host.

**Comment by dgiantsidi** [comment]
Thank you!
