### ISSUE TITLE
Replys do not contain signatures or macs

### ISSUE THREAD

**Issue by RjRDRG** [bft-smart/library#97]
System.config parameter useSignatures and useMac as no effect on server replys, only on client requests
A separate system.config parameter for replys would be ideal

```
/ replies are not signed in the current JBP version
sm.signed = false;
// produce signature if necessary (never in the current version)
if (sm.signed) {
	byte[] signature = TOMUtil.signMessage(privKey, data);
	sm.serializedMessageSignature = signature;
}
```

https://github.com/bft-smart/library/blob/master/src/main/java/bftsmart/communication/client/netty/NettyClientServerCommunicationSystemServerSide.java

**Comment by bergerch** [comment]
Hi, note that the client <---> server connections are secured through the use of TLS (messages are encrypted and their integrity is protected by the use of message authentication codes). In short: messages that come from the server will can be always authenticated and their integrity is protected.

The reason why there is an option to add signatures to client _requests_ is to account for the possibility of malicious _clients_. Malicious clients could try to prevent that requests are correctly disseminated to all replicas, and in fact, this can lead to enforced leader changes: if a leader has not seen a request, it will not order it, and then be blamed by other replicas that received the request. However, if client requests are signed, then signature makes sure that this request can be authenticated by all replicas, thus it is possibly to forward the request to other replicas that did not receive it.

**Comment by rvassantlal** [comment]
Hi, 
End-to-end authentication can be provided by signing responses at the service level. Currently, I am not seeing if signing responses are useful in general.

The encryption can be deactivated using this cipher set [#system.ssltls.enabled_ciphers = TLS_ECDHE_ECDSA_WITH_NULL_SHA,](https://github.com/bft-smart/library/blob/e54433880a770a6e1dd64011d438ff45ff85ec44/config/system.config#L204). However, this might require changing your java configurations to use tls without encryption.
